/* museum-data.js - the content of the two museums.
   To record a new site update in the Update Museum, add an entry to the end of UPDATE_SEEDS
   (give it a new unique id). Existing visitors will see it appear automatically. */

const UPDATE_SEEDS = [
  {
    id: "up-01-sketch",
    date: "2026-10-06",
    title: "The First Sketch",
    year: "Oct 2026",
    medium: "Planner foundation",
    description: "The planner is born from a hand-drawn sketch: a greeting header with live date, time and day, a monthly calendar, and a notes panel that opens when you press a day.",
    link: "planner.html",
    image: "assets/notes-icon.gif",
    pixel: true,
  },
  {
    id: "up-02-colors",
    date: "2026-10-06",
    title: "Busy and Done",
    year: "Oct 2026",
    medium: "Calendar colors",
    description: "Weekdays and weekends get their own colors. Adding a task turns a day red for busy, and finishing every task turns it cyan.",
    glyph: "✓",
    bg: "linear-gradient(135deg, #b3262e, #1fa5ad)",
  },
  {
    id: "up-03-flip",
    date: "2026-10-06",
    title: "The Page Flip",
    year: "Oct 2026",
    medium: "Calendar animation",
    description: "The month arrows moved below the calendar, and changing month now flips the page like a real wall calendar.",
    link: "planner.html",
    image: "assets/arrow.png",
    pixel: true,
    backdrop: "linear-gradient(135deg, #f2d479, #b8902a)",
  },
  {
    id: "up-04-frames",
    date: "2026-10-06",
    title: "Pixel Frames",
    year: "Oct 2026",
    medium: "Header artwork",
    description: "The date, time and day boxes were dressed in a pixel-art frame, stretched cleanly to fit any size.",
    link: "planner.html",
    image: "assets/dtd-frame.png",
    pixel: true,
    backdrop: "linear-gradient(135deg, #f2d479, #b8902a)",
  },
  {
    id: "up-05-add",
    date: "2026-10-06",
    title: "The Plus Button",
    year: "Oct 2026",
    medium: "Custom buttons",
    description: "Hand-picked artwork replaced the plain buttons: a yellow plus for adding tasks and a notes pad icon beside the notes heading.",
    link: "planner.html",
    image: "assets/add-btn.png",
    pixel: true,
  },
  {
    id: "up-06-background",
    date: "2026-10-06",
    title: "Your Own Wall",
    year: "Oct 2026",
    medium: "Custom backgrounds",
    description: "Any picture can now become the page background. It is shrunk, remembered between visits and removable with one click.",
    glyph: "BG",
    bg: "linear-gradient(135deg, #3a1c71, #d76d77, #ffaf7b)",
  },
  {
    id: "up-07-theme",
    date: "2026-10-06",
    title: "Gold and Black",
    year: "Oct 2026",
    medium: "Theme and fonts",
    description: "The whole site moved to a gold and black theme with the Patrick Hand doodle font, wobbly hand-drawn borders and deeper status colors.",
    link: "planner.html",
    glyph: "Au",
    bg: "linear-gradient(135deg, #0a0a0a, #8a7222, #f2d479)",
  },
  {
    id: "up-08-focus",
    date: "2026-10-06",
    title: "Focus Mode",
    year: "Oct 2026",
    medium: "New page",
    description: "A lock-in timer with adjustable focus and rest periods, a moon button to reach it, and a session counter for the day.",
    link: "focus.html",
    image: "assets/focus-btn.gif",
    pixel: true,
  },
  {
    id: "up-09-rgb",
    date: "2026-10-06",
    title: "RGB Glow",
    year: "Oct 2026",
    medium: "Effects",
    description: "The running timer glows in sweeping rainbow colors, and calendar dates and boxes light up in RGB when hovered.",
    link: "focus.html",
    glyph: "RGB",
    bg: "linear-gradient(90deg, #ff2d55, #ff9500, #ffee00, #34ff6a, #00e5ff, #3b6bff, #c04bff)",
  },
  {
    id: "up-10-museums",
    date: "2026-10-06",
    title: "The Museums",
    year: "Oct 2026",
    medium: "New pages",
    description: "A grand hall with two museums: this one for every update made to the site, and another for projects built elsewhere.",
    link: "gallery.html",
    glyph: "M",
    bg: "linear-gradient(135deg, #17110a, #5c4510, #d4af37)",
  },
  {
    id: "up-11-fit",
    date: "2026-10-06",
    title: "Frames That Fit",
    year: "Oct 2026",
    medium: "Museum polish",
    description: "Frames in the museums now take the shape of each picture, and screenshots from Snipping Tool can be pasted straight into the donate form with Ctrl+V.",
    link: "gallery.html",
    glyph: "Ctrl+V",
    bg: "linear-gradient(135deg, #1d1a30, #7c5c12, #f6dc86)",
  },
  {
    id: "up-12-settings",
    date: "2026-10-06",
    title: "The Settings Panel",
    year: "Oct 2026",
    medium: "Backgrounds",
    description: "Calendar and notes backgrounds can be switched on and off, faded with a transparency slider, and the calendar can show a different picture for each month.",
    link: "planner.html",
    glyph: "Set",
    bg: "linear-gradient(135deg, #14110a, #2f7d55, #d4af37)",
  },
  {
    id: "up-13-plan-ahead",
    date: "2026-10-06",
    title: "Plan Ahead",
    year: "Oct 2026",
    medium: "Planner features",
    description: "A Today button, repeating tasks (daily, weekdays, weekly, monthly), a search across every note and task, and an Agenda showing what is overdue and what is coming in the next two weeks.",
    link: "planner.html",
    glyph: "↻",
    bg: "linear-gradient(135deg, #0a0a0a, #1fa5ad, #f2d479)",
  },
  {
    id: "up-14-open-to-all",
    date: "2026-10-06",
    title: "Open to Everyone",
    year: "Oct 2026",
    medium: "Hosting and access",
    description: "The font now ships with the site so it works offline and online, the calendar days work with the keyboard and arrow keys, dim text is easier to read, and the code was reorganized so it can be hosted anywhere.",
    link: "planner.html",
    glyph: "www",
    bg: "linear-gradient(135deg, #17110a, #3a1c71, #d4af37)",
  },
  {
    id: "up-15-outline-color",
    date: "2026-10-06",
    title: "Pick Your Color",
    year: "Oct 2026",
    medium: "Outline color",
    description: "The gold outlines, headings and buttons can now be any color. Pick a preset or a custom color in Settings, and every page follows. Backups include your choice.",
    link: "planner.html",
    glyph: "RGB",
    bg: "linear-gradient(135deg, #e8638f, #2ec4d6, #8fd14f)",
  },
  {
    id: "up-16-game-night",
    date: "2026-10-08",
    title: "Game Night",
    year: "Oct 2026",
    medium: "Grand Hall and polish",
    description: "The Grand Hall doors became pixel-art gold frames holding an hourglass and a retro computer, the museums got 8-bit sound effects, every page got a game-style loading screen, and the site was tuned to run smoothly on phones.",
    link: "gallery.html",
    image: "assets/door-updates.png",
    pixel: true,
  },
  {
    id: "up-17-cloud-sync",
    date: "2026-10-08",
    title: "Everywhere at Once",
    year: "Oct 2026",
    medium: "Cloud sync",
    description: "Sign in with Google or email and your planner, notes, museums and settings follow you between your phone and computer automatically.",
    link: "planner.html",
    glyph: "☁",
    bg: "linear-gradient(135deg, #0a0a0a, #2b5876, #d4af37)",
  },
  {
    id: "up-18-turntable",
    date: "2026-10-11",
    title: "The Turntable",
    year: "Oct 2026",
    medium: "Spotify player",
    description: "Focus Mode got a Spotify mini player: a spinning record with a tonearm that drops when the music plays, under a frosted glass Now Playing card.",
    link: "focus.html",
    glyph: "♫",
    bg: "linear-gradient(135deg, #0a0a0a, #1db954, #d4af37)",
  },
  {
    id: "up-19-mission-control",
    date: "2026-10-11",
    title: "Mission Control",
    year: "Oct 2026",
    medium: "Life dashboard",
    description: "The site became a personal operating system: a home dashboard with a daily progress ring, countdowns and weekly stats, a menu bar on every page, a Project Workshop, a Daily Reflection journal and a Knowledge Vault.",
    link: "index.html",
    glyph: "◎",
    bg: "linear-gradient(135deg, #0a0a0a, #d4af37, #1fa5ad)",
  },
  {
    id: "up-20-lock-in",
    date: "2026-10-11",
    title: "Lock-In Room",
    year: "Oct 2026",
    medium: "Focus, XP and timeline",
    description: "Focus Mode grew into the Lock-In Room with linked tasks, ambient sounds, a distraction list and reflections. XP, levels and badges reward finished work, and a Life Timeline with a time machine looks back at any day.",
    link: "focus.html",
    glyph: "XP",
    bg: "linear-gradient(135deg, #3a1c71, #d4af37, #0a0a0a)",
  },
];

const WINGS = {
  updates: {
    storeKey: "plannerUpdates",
    seeds: UPDATE_SEEDS,
    pageTitle: "The Update Museum",
    small: "Chronicle of Changes",
    title: "The Update Museum",
    sub: "Every update made to this website, framed in order",
    empty: "No updates hang here yet.",
    addLabel: "Record an update",
    formHeading: "Record an update",
    editHeading: "Amend this update",
    visitLabel: "See it in action",
    lblYear: "Date",
    lblMedium: "What changed",
    ph: { title: "Name of the update", year: "Oct 2026", medium: "Calendar, theme, new page...", desc: "What changed and why?" },
  },
  projects: {
    storeKey: "plannerProjects",
    seeds: [],
    pageTitle: "The Museum of Projects",
    small: "Works Beyond This Site",
    title: "The Museum of Projects",
    sub: "Websites built by the artist, hung with pride",
    empty: "No projects hang here yet. Donate your first website below.",
    addLabel: "Donate a project",
    formHeading: "Donate a project",
    editHeading: "Restore this project",
    visitLabel: "Visit the website",
    lblYear: "Year",
    lblMedium: "Built with",
    ph: { title: "Name of the website", year: String(new Date().getFullYear()), medium: "HTML, CSS, JavaScript", desc: "What is it, and what does it do?" },
  },
};
